version: "3"

dotenv: [".env"]

tasks:
  demo:
    desc: Open MCP Inspector for the cai-tools server defined in mcp.json
    cmds:
      - uv run python -m demo.app

  clear-cache:
    desc: Clear the cache directory
    cmds:
      - cd data/original && rm -rf -- */

  compare:
    desc: Compare two songs and generate a similarity report
    cmds:
      - uv run python -m vibematcher.comparison.compare
